name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.12-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin123
          POSTGRES_PASSWORD: admin123
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: npm install, build, and test
        run: |
          npm ci
          npm run compile
          npm run migrate:test
          npm run test
        env:
          DATABASE_URL: postgresql://admin123:admin123@localhost:5432/test
          CI: true
